### PR TITLE
Fix confusing names

### LINKED ISSUE #526: auth/jwt: Function names not intuitive.
I've been using the auth/jwt package on a project for a while now and I constantly trip over the difference between `FromHTTPContext` and `ToHTTPContext`. The structure of the names don't help me remember which way the data is flowing.

From godoc:

----------

```go
func FromHTTPContext() http.RequestFunc
```
FromHTTPContext moves JWT token from context to request header. Particularly useful for clients.

```go
func ToHTTPContext() http.RequestFunc
```
ToHTTPContext moves JWT token from request header to context. Particularly useful for servers.

------------

I'd prefer the following renaming of these functions (and the corresponding gRPC pair):

`FromHTTPContext` -> `ContextToHTTP`
`ToHTTPContext` -> `HTTPToContext`

Do others find the current names confusing also?
Does anyone have better suggestions that mine?

### PR DESCRIPTION
**Pull request by peterbourgon**
Closes #526.

@ChrisHines @basvanbeek — interested in a review?

@willfaught @terinjokes — likewise, and FYI.

### CODE REVIEW

**Comment by peterbourgon** [comment]
For the record,

```fish
#!/usr/bin/env fish

for pair in \
    "FromHTTPContext ContextToHTTP" \
    "ToHTTPContext   HTTPToContext" \
    "FromGRPCContext ContextToGRPC" \
    "ToGRPCContext   GRPCToContext" \
    "FromHTTPRequest HTTPToContext" \
    "ToHTTPRequest   ContextToHTTP" \
    "FromGRPCRequest GRPCToContext" \
    "ToGRPCRequest   ContextToGRPC"
  set fr (echo $pair | awk '{print $1}')
  set to (echo $pair | awk '{print $2}')
  echo change from $fr to $to
  find . -type f -name '*.go' -exec sed -i '' s/$fr/$to/ \{\} +
end
```

File: auth/jwt/transport.go [hunk 1]
```diff
@@ -17,9 +17,9 @@ const (
 	bearerFormat string = "Bearer %s"
 )
 
-// ToHTTPContext moves JWT token from request header to context. Particularly
+// HTTPToContext moves JWT token from request header to context. Particularly
```
Comment (ChrisHines) [inline auth/jwt/transport.go]: I feel obligated to point out that JWT is an acronym for JSON Web Token, which makes the phrase "JWT token" repetitive. I believe a more grammatically correct phrasing is "... moves a JWT from request header to context."

Comment (peterbourgon) [inline auth/jwt/transport.go]: Fixed. Thank you.

File: auth/jwt/transport.go [hunk 2]
```diff
@@ -17,9 +17,9 @@ const (
 	bearerFormat string = "Bearer %s"
 )
 
-// ToHTTPContext moves JWT token from request header to context. Particularly
+// HTTPToContext moves a JWT from request header to context. Particularly
```
Comment (willfaught) [inline auth/jwt/transport.go]: Seems like you'd want to keep the "a" article use consistent—either use them everywhere or nowhere ("a request header", "a context").

File: auth/jwt/transport.go [hunk 3]
```diff
@@ -17,9 +17,9 @@ const (
...
 // useful for servers.
-func ToHTTPContext() http.RequestFunc {
+func HTTPToContext() http.RequestFunc {
```
Comment (willfaught) [inline auth/jwt/transport.go]: Just curious, and this isn't part of the review for this PR, why have ToHTTPContext/HTTPToContext return the RequestFunc instead of be the RequestFunc? It always returns the same function value with no side effects.

File: auth/jwt/transport.go (hunk 2 above)
Comment (willfaught) [inline auth/jwt/transport.go]: I see, it's for consistency with the others. Learning as I go. :)

Comment (willfaught) [inline auth/jwt/transport.go]: The "a" article use is now inconsistent (present with "JWT", absent with "request header" and "context"), not sure if that's intentional, not a big deal.

File: auth/jwt/transport.go (hunk 3 above)
Comment (willfaught) [inline auth/jwt/transport.go]: "Context" seems to be in all of these names, so is it redundant? Would To/FromHTTP and To/FromGRPC be equally clear? I haven't taken a close look at the whole file, and I've never used the package, so I'm genuinely asking. :) If not, the names look good!
